useSidebarSearch: true
showVersion: false
primaryColor: '#B10000'
trianglifyOptions:
  x_colors: ['#000', '#B10000', '#000']
extraCss:
  - 'assets/css/asciidoc-admonitionblock.scss'
social:
  twitter: 'CamundaBPM'
  github: 'camunda/camunda-rest-client-spring-boot'
  other:
    - link: 'https://camunda.github.io/camunda-rest-client-spring-boot/'
      label: 'Home'
      icon: 'fas fa-home'
menu:
  - type: 'page'
    itemId: 'Quick Start'
    title: 'Quick Start'

  - type: 'submenu'
    title: 'Introduction'
    menu:
      - type: 'wiki'
        section: 'introduction'

  - type: 'submenu'
    title: 'User Guide'
    menu:
      - type: 'wiki'
        section: 'user-guide'

  - type: 'submenu'
    title: 'Developer Guide'
    menu:
      - type: 'wiki'
        section: 'developer-guide'

  - type: 'submenu'
    title: 'Explore'
    menu:
      - type: 'page'
        title: 'Changelog'
        itemId: 'Changelog'
      - type: 'page'
        title: 'License'
        itemId: 'License'
